### ISSUE TITLE
Eliminar dropdown de maestría

### ISSUE THREAD

**Issue by rudygodoy** [cs-ucsp/rics-ucsp#3]
Eliminar dropdown de maestría y mostrar menú como tab lateral a la izquierda.

**Comment by rudygodoy** [comment]
@alfa3 Si sacamos el submenú a la izquierda en móviles no se ve bien. Confirmar si lo hacemos o no.

**Comment by alfa3** [comment]
Que tal Rudy,

Por favor ve la manera de poder colocarlo como te indicamos. Si no se
muestra bien en los celulares, buscar algun plugin, que lo permita
visualizar.

Saludos.

2015-06-04 17:16 GMT-05:00 Rudy Godoy notifications@github.com:

**Comment by yurigomez** [comment]
¿quién es alfa3?

**Comment by rudygodoy** [comment]
@yurigomez es Carlos Begazo del CICC.

**Comment by eLRuLL** [comment]
quien es @yurigomez ? :smile: :smile:

**Comment by rudygodoy** [comment]
@yurigomez es Yuri Gomez.
